### ISSUE TITLE
Questions to run code

### ISSUE THREAD

**Issue by RongxinZhang** [mit-dci/utreexo#1]
Hi @adiabat ,

I'm trying to run the code and have several questions:

1. Should I first run `cmd/ibdsim/ibdsim.go` and then run `cmd/txottlparse.go`
2. Where can I download `ttl.mainnet.txos`? I'm assuming this is the full Bitcoin UTXO set?
3. Do you have an example file of how this can be implemented?
4. I'm unclear between the difference between a `forest` and a `pollard`. From the readme, it seems to be the only difference is that pollard is a `light-client` where it just stores a subset of the full UTXO set?

Thank you!

**Comment by adiabat** [comment]
Hi - I added blockparse, which is where you can generate the initial txos file.

Also, yup, pollard is the mini node, and forest will be the bridge node.  Though it might make sense to get rid of forest, as pollard should be able to do both.  Forest might be more efficient though.
