### ISSUE TITLE
firstPass() and secondPass() not found in cmd/txottl/{txottl.go,txottlparse.go}

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#10]
cmd/txottl/readme.md states

> You have to compile with firstPass() and then comment it out and compile with secondPass() to get a different executable and run them sequentially.

But git grep only returns with that md file. Not quite sure how to build.

**Comment by adiabat** [comment]
Thanks for catching that -- I moved things around and hadn't changed the readme.  The txottl binary now only performs the function of secondPass(), as blockparser now does what firstPass() did.
(when it works, which I'm not sure blockparser does reliably...)

Will update readme

**Comment by kcalvinalvin** [comment]
What's supposed to happen when blockparser works?

I've been trying to get the ibdsim to work but couldn't so far. Hacking things around atm

**Comment by adiabat** [comment]
Hi - 
I posted a quick walkthrough in readme.md -- hopefully that answers some questions; if you have other questions or things don't work, let me know and I'll try to fix them.
