### ISSUE TITLE
forest.go: Writing to root directory won't work on macOS Catalina and newer

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#104]
https://github.com/mit-dci/utreexo/blob/565a2dd2a976f086043b9a94a86d913495b6ad19/utreexo/forest.go#L89

It works fine on my Linux machine but macOS doesn't let you write to ```/``` anymore (and it's not changeable).

Might want to consider something else for macOS compatibility.

**Comment by adiabat** [comment]
Ah right that's very linux specific.  

Also I need to change a bunch of stuff... the whole readme I wrote about leaf data is wrong.  Probably should just leave it a hash map...

**Comment by adiabat** [comment]
OK got rid of the whole f.positions interface entirely, going back to in-memory hashmap for positions.  Two steps forward, one step back.
But then 2 more forward so it's OK.

**Comment by adiabat** [comment]
fixed (f.positions is no more) in #102
