### ISSUE TITLE
idbsim throws errer. no proofdb/ found

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#11]
https://github.com/mit-dci/utreexo/blob/b0149d6f5b076208acf90e211af0b899f76a5a5d/cmd/ibdsim/ibdsim.go#L68

Should update the readme to mention that you need to run ibdsim -genproofs to generate proofdb when testing the ibdsim

**Comment by adiabat** [comment]
fixed in 71f49e5
thanks for catching that!
