### ISSUE TITLE
variable delHashes never initialized in genproofs.go

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#119]
Function ```genDels()``` in ```genproofs.go``` has variable delHashes as a named return.

https://github.com/mit-dci/utreexo/blob/7807032a59d52eb3fe6f98f0e6345a50c61c995b/bridgenode/genproofs.go#L289-L290

This just never gets any value assigned to it so it's always nil. This ends up in function ```ProveBatch()``` in proving nothing.

**Comment by kcalvinalvin** [comment]
I think this was one of the bugs I was coming across

**Comment by adiabat** [comment]
Huh yeah that's a dumb mistake.  Easy to fix though!

**Comment by adiabat** [comment]
fixed in f44be32c2adc785be619eed341a8dad5512fecc5
