### ISSUE TITLE
'panic: varint is 1' generating proofs on mainnet

### ISSUE THREAD

**Issue by ecdsa** [mit-dci/utreexo#142]
```
Building offsetfile... blk02092.dat
Dead end tip. Exiting...
Building offsetfile... blk02093.dat
got non magic bytes 00000000, finishing
Dead end tip. Exiting...
Building offsetfile... blk02094.dat
blk02094.dat doesn't exist; done building
tip height 437108
Creating new forestdata
Building Proofs and ttldb...
remap forest 0 rows -> 1 rows
remap forest 1 rows -> 2 rows
remap forest 2 rows -> 3 rows
remap forest 3 rows -> 4 rows
remap forest 4 rows -> 5 rows
remap forest 5 rows -> 6 rows
remap forest 6 rows -> 7 rows
remap forest 7 rows -> 8 rows
panic: varint is 1

goroutine 77 [running]:
github.com/mit-dci/utreexo/util.BlockAndRevReader(0xc000062780, 0xaa0006ab74)
	/home/boltz/go/src/github.com/mit-dci/utreexo/util/utils.go:100 +0x23a
created by github.com/mit-dci/utreexo/bridgenode.BuildProofs
	/home/boltz/go/src/github.com/mit-dci/utreexo/bridgenode/genproofs.go:72 +0x317

```

**Comment by kcalvinalvin** [comment]
hmmm... the error message is vague (and should be improved) but it means that a TxInUndo in your particular rev file happened to have a varint that isn't 0 for an older version of tx from Bitcoin Core. [reference core code](https://github.com/bitcoin/bitcoin/blob/9cc7eba1b5651195c05473004c00021fe3856f30/src/undo.h#L42)

Was this on testnet? Did you originally sync the chain years ago? The codebase at the moment isn't handling edge cases in reading the rev*.dat files very well so this issue could be by a synced chain from a long time ago.

**Comment by ecdsa** [comment]
indeed it was on mainnet (see title). the older rev*.dat files are from 2016.
