### ISSUE TITLE
4GB of ram requirement stated in cmd option forestInRam

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#153]
https://github.com/mit-dci/utreexo/blob/1d5e26618e3eba3d71480ece3c139f43f41d872b/cmd/utreexoserver/bridgeserver.go#L40-L41

In my testing, I'm getting around 10GBs of memory usage by ```utreexoserver``` when syncing testnet3 to block ~1,700,000. Maybe requiring 16GBs of memory is more realistic?

**Comment by adiabat** [comment]
How many UTXOs are in testnet3?  10GB is pretty big!  Yeah 4GB is not realistic I guess, we could also just say "lots of ram"

**Comment by adiabat** [comment]
Changed to "lots" in e438f5f5b90aaac754d5243d39f4b62e8442e624 because any specific number is probably wrong.
