### ISSUE TITLE
remap forest hangs with diskForestCache

### ISSUE THREAD

**Issue by adiabat** [mit-dci/utreexo#155]
I was syncing testnet from the start with current master (61229d15b8e92d8619b6e6f5e66ca7747c6ddec0)

Around block 1149501 I get:
```remap forest 24 rows -> 25 rows```
and it stops there, staying at 100% CPU usage.  Seems reproduceable with multiple runs.

Might have something to do with the size? 25 rows is 2GB, which was a size cuttof I found file.Read() wouldn't read.  So it's possibly the `flushCacheToDisk()` called by resize is failing because it's trying to do very large writes.  

Not sure though because it seems like it'd fail in a different way, not get stuck at 100% cpu.

**Comment by dergoegge** [comment]
> Might have something to do with the size? 25 rows is 2GB, which was a size cuttof I found file.Read() wouldn't read. So it's possibly the flushCacheToDisk() called by resize is failing because it's trying to do very large writes.

pretty sure that's the issue. also the limit is documented here: https://github.com/golang/go/blob/fcdb6aa6ee5ddeacc7472e38c0065b63e9d954ce/src/internal/poll/fd_unix.go#L142

**Comment by dergoegge** [comment]
> Not sure though because it seems like it'd fail in a different way, not get stuck at 100% cpu.

hm. yeah it should just fail and not go to 100% cpu usage.

**Comment by adiabat** [comment]
I tried again on a different machine (more cpus / ram) and it got through it OK.  I'll try to reproduce on the old machine a few times.  Maybe it just takes a really long time to remap on a slower cpu?  Which also isn't great but not really a bug then.

**Comment by dergoegge** [comment]
i was able to reproduce(sort of), the remap from 24 to 25 does indeed take a while, ~1min on the machine i tested on so if you tested on a slower machine it could seem like it is stuck. I also tested without cache and it's just as slow so it's not a cache issue.

**Comment by adiabat** [comment]
Yeah I got it to work on mine -- it took several minutes at 100% cpu.  Anyway not a bug, just slow.  But seems too slow, as it's only moving around a couple gigabytes of data in ram, which shouldn't take minutes... 
Anyway will close and keep an eye on profiling / optimizing remap
