### ISSUE TITLE
Forest: Revamp disk storage

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#191]
In my testing of syncing forest on mainnet, it took over a week and failed ultimately when my computer crashed and broke the ssh pipe to the vps. In order for bridgenodes to be useable, this should be fixed.

Current implementation:

Forest on disk has a really naive implementation in that every node in the tree is updated by accessing each individual node by its offset on disk.

This results in lots of tiny reads from the disk, making a huge disk bottleneck.

cacheForestData helps but it still keeps the naive implementation in where individual nodes are fetched one-by-one if it's not in the cache.

# Idea: Implement a copy on write disk forest 

## Overall structure

Memtable: Loaded to memory on startup. Contains metadata on tree size, offsets, filenames, etc.

Tree-table: A on-disk file table which are limited to 2048 kilobytes. This is the representation of the tree on disk.

Tree-block: A tree with 127 nodes and 32 bytes of metadata. This takes up 4096 bytes, the typical block size on modern computers.

A tree-block can be a six-tree. A height 10 tree with six-trees look like so:
```
2047
|-------------------------------\
2045                            2046
|---------------\               |---------------\
2041            2042            2043            2044
|-------\       |-------\       |-------\       |-------\
2045    2034    2035    2036    2037    2038    2039    2040
|---\   |---\   |---\   |---\   |---\   |---\   |---\   |---\
st  st  st  st  st  st  st  st  st  st  st  st  st  st  st  st
```
Each ```st``` is contains the file name of the tree-table and offset in that file.

A memory representation of a height 7 tree:
```
255
|----\
st   st
```
Each six-tree is not aware of its position inside the whole utreexo forest.
The memtable contains information about the position of each st.

Only the last six-tree can have empty nodes. In a tree like so:
```
2047
|-------------------------------\
2045                            em
|---------------\               |---------------\
2041            2042            2043            em
|-------\       |-------\       |-------\       |-------\
2045    2034    2035    2036    2037    2038    2039    em
|---\   |---\   |---\   |---\   |---\   |---\   |---\   |---\
st  st  st  st  st  st  st  st  st  st  st  st  st  st  st  em
```
the #14 st may look like
```
em
|-------------------------------\
em                              em
|---------------\               |---------------\
em              em              em              em
|-------\       |-------\       |-------\       |-------\
em      em      em      em      em      em      em      em
|---\   |---\   |---\   |---\   |---\   |---\   |---\   |---\
00  em  em  em  em  em  em  em  em  em  em  em  em  em  em  em
```
Each position is calculatable by:
```
(64 * st pos) + pos inside st
```
which is similar to an operating system tlb translation.

so the 0th position in #14 st would be at pos 896 as
```
(64 * 14) + 0
```

These six-trees in turn can be combined to be twelve-trees.

twelve-tree: The second smallest tree structure with 64 six-trees and a height of 12. Takes up 4096 bytes, the size of a typical block size on modern computers.

Each twelve-tree can hold 4095 nodes

A memory representation of a height 13 tree:
```
8191
|-------\
tt      tt
```
A memory representation of a height 16 tree:
```
65535
|-------------------------------\
65533                           65534
|---------------\               |---------------\
65529           65530           65531           65532
|-------\       |-------\       |-------\       |-------\
65521   65522   65523   65524   65525   65526   65527   65528
|---\   |---\   |---\   |---\   |---\   |---\   |---\   |---\
tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt
```
Each twelve-tree is not aware of its position inside the whole utreexo forest. The memtable contains information about the position of each tt.

This method can be extended as much as it's needed.

## Updating a leaf in this system

Ex: Deleting 0th leaf in the tree below. For sake of this example, the last tt does not have empty nodes.
```
65535
|-------------------------------\
65533                           65534
|---------------\               |---------------\
65529           65530           65531           65532
|-------\       |-------\       |-------\       |-------\
65521   65522   65523   65524   65525   65526   65527   65528
|---\   |---\   |---\   |---\   |---\   |---\   |---\   |---\
tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt  tt
```
1. Access tt #0
2. Access st #0
3. Delete pos 0. Mark st #0 as having empty
4. Mark tt #0 as having empty
5. Swap tt #15 and tt #0

This can be extended to more complicated batch deletions.

1. Process each st with the transform code. Then mark as having deletions or not 
2. Process each tt with the transform code which have st's marked as having deletions. 
3. Apply deletions
4. Profit

The transform operations are the same as the current system. It's just that the file is handled differently.

### Writing to disk

1. Append new tree-block #15 and #0 to the last tree-table on disk. If tree-table is full (over 2048 kilobytes), then make a new tree-table.
2. Memtable is updated to include the new file name (if needed) and offset of the tree-block

Old tree-tables/tree-blocks can be cleaned up based on a user-configurable number of times. Ex. Every 10 blocks, the stale tree-tables/tree-blocks are deleted. The user may choose not to delete the old trees in order to serve proofs.

## Improved areas

1. Very straightforward caching strategy.

2. Easy undo/re-org handling if one chooses to store the old state

3. No need to store the proofs separately since it is addressable if the old tree-blocks are kept.

4. Calling ```reMap``` when moving down is ok now since a reMap isn't very expensive

**Comment by adiabat** [comment]
Implemented in COW
