### ISSUE TITLE
error in AddOne in utrexo.pdf

### ISSUE THREAD

**Issue by dooglus** [mit-dci/utreexo#2]
I was reading through the PDF of the paper trying to understand it and I think I found an error in "Algorithm 1 AddOne".

Shouldn't lines 8 and 9 be switched?

**Comment by dooglus** [comment]
Algorithm 2 DeleteOne doesn't seem right either. Shouldn't `acc[h]` be set to be empty after line 11 runs?

**Comment by dooglus** [comment]
Page 13 has "prrofs" instead of "proofs".

**Comment by adiabat** [comment]
Yup, you're right about all of these!  I've corrected the paper and uploaded the fixed version in a85743b -- thanks!
