### ISSUE TITLE
What is the inclusion proof argument of DeleteOne()?

### ISSUE THREAD

**Issue by zzxiang** [mit-dci/utreexo#26]
I'm reading and translating the PDF of the paper into Chinese and I don't quite understand what the proof argument of DeleteOne() is.

It is written in the paper that the argument is "an inclusion proof of the element to be deleted", and "is also a list of hashes, along with a position index indicating which proof elements are right and which are left Parent() argument". But I still don't know what the hashes are. And seems that the position index is not used in Algorithm 2 DeleteOne(). The proof elements always become the left argument of Parent().

So what is the exact definition of the inclusion proof and how are the hashes in it computed? Or are there any references on it I can refer to?

Thanks in advance.

**Comment by zzxiang** [comment]
Sorry, I got it. That is a basic concept of Merkle trees. The argument is an array of hashes which prove the deleted node is a leaf of a Merkle tree. For example, in the following figure, the inclusion proof of H<sub>K</sub> is {H<sub>L</sub>, H<sub>IJ</sub>, H<sub>MNOP</sub>, H<sub>ABCDEFGH</sub>}.

![image](https://user-images.githubusercontent.com/10098144/68119196-6727d200-ff45-11e9-812c-2cdd36690203.png)

**Comment by kcalvinalvin** [comment]
Eh might as well post anyways for future reference.

To answer your question, let's go over Utreexo.

1) Utreexo changes the construction of a merkle tree.
        a) In a typical Bitcoin fashion, you would do 
```
                   A
                  /  \
                B     C
               / \    |   
              D   E   F
             / \ / \ / \
             1 2 3 4 5 6
```

        b) In Utreexo, you would do

```
k
| \
|   \
h   i    j
| \ | \  | \  
a b c d  e f  g

actually stored data:

k
| \
|   \
?   ?    j
| \ | \  | \  
? ? ? ?  ? ?  g
```

Those ? are actually present, but we don't keep them in our disk. When someone wants to prove that they own d, they would have to provide the **the position index, hash of the UTXO, and the sibling hashes up to a root**. That would be the definition of an "inclusion proof".

On the example provided above, if you wanted to prove that you indeed control the UXTO d, you would provide (aka. inclusion proof): 

1) Position index - 1
2) Hash of itself - hash(d)
3) Hash of the siblings - hash(c), hash(h), hash(i)

Currently, the actual implementation code (function VerifyBlockProof), requires more than these 3 inputs but that's just implementation details. It's bound to change later on as well.

>So what is the exact definition of the inclusion proof and how are the hashes in it computed?
To add to what is stated above, an inclusion proof is what you would send to the network to prove that you control the private key to a particular UTXO.

>And seems that the position index is not used in Algorithm 2 DeleteOne().
In the paper it is defaulted to 0 to simplify things as stated in *paragraph 2, 4.2 Adding and removing elements*. h (aka height) would be the position index.

>The proof elements always become the left argument of Parent().
Parent() is just concatenating and hashing it like in normal Bitcoin merkle tree fashion. Which comes first *when constructing the merkle tree* wouldn't matter so the proof elements can either be left or right.

**Comment by zzxiang** [comment]
Thanks for your detailed explanation!

But I thought the position index of UTXO d in your example should be 2, as the root in position 1 is j. Am I missing something?

**Comment by zzxiang** [comment]
Also, seems that providing hash(i) is not necessary as it can be computed from hash(c) and hash(d).

**Comment by kcalvinalvin** [comment]
Edited

**Comment by zzxiang** [comment]
Em...so, why the position index is 3?

**Comment by zzxiang** [comment]
Is it the position index of d among all the leaves a~g?

**Comment by kcalvinalvin** [comment]
> Is it the position index of d among all the leaves a~g?

The way it is currently implemented in utreexo, yes. It can be implemented so that you treat the roots as separate trees but it isn't done that way in this repo.
