### ISSUE TITLE
Typo in section 5.6 of the paper

### ISSUE THREAD

**Issue by zzxiang** [mit-dci/utreexo#27]
It is written in the last sentence of the fourth paragraph of section _5.6 Hardening against collision attacks_ that

> If we can restrict the attacker’s ability to create either side of the collision (the hash being inserted or the hash being falsely proven) this attack is no longer feasable.

`feasable` should be `feasible`.

**Comment by adiabat** [comment]
fixed in 2fd2079609d49cc88aa716e14de8e593ab3be419, thanks!
