### ISSUE TITLE
Some inquiries about the outputs of a Utreexo run

### ISSUE THREAD

**Issue by Shymaa-Arafat** [mit-dci/utreexo#270]
Can u clarify the meaning of each output more?
![IMG_20210514_162612](https://user-images.githubusercontent.com/83260375/118345287-a324f580-b533-11eb-968f-b07efa126aaa.jpg)
r we getting it right?
no of insertions, deletions, UTXOs in this block, how many trees in the forest, max & min heights?
What is "re", "ow", "total"?
.
If so, I think u probably made some plots/statistics for the 1st 3(add,del, UTXO) with each block?can u guide us to them?
.
Also, from here
https://bitcointalk.org/index.php?topic=5334763.new;topicseen#new
you can read that there was some problems in running the code, 

> EDIT: Apparently it is using so much resources that it managed to crash my machine and force me to do a power cycle.
Rep
.
can u explain what was done wrong?
.
Thank u for ur time, and sorry if I caused any distraction to ur work.

**Comment by kcalvinalvin** [comment]
I left a reply on the bitcointalk thread as well. Copied over from that reply.

Block 180000 -> The current height it's at
add -> all the added leaves (TXOs)
del -> all the deletions that happened (STXOs)
pol nl -> pollard numLeaves. All the current UTXOs
roots -> Utreexo roots
he -> Height. Height of the Utreexo tree
re -> RememberEver. The count of all the leaves remembered through caching. This is stale and we have a newer caching algorithm.

>  If so, I think u probably made some plots/statistics for the 1st 3(add,del, UTXO) with each block?can u guide us to them?

I assume you're referring to #257? If plots of additions/deletions for a block is what you're looking for, 257 isn't that. We currently don't have any plots of such data.

> you can read that there was some problems in running the code,

    EDIT: Apparently it is using so much resources that it managed to crash my machine and force me to do a power cycle.
    Rep
    .
    can u explain what was done wrong?
    .
    Thank u for ur time, and sorry if I caused any distraction to ur work.


Yes that's a known problem #264. We're looking to deprecate that code.

**Comment by Shymaa-Arafat** [comment]
Thanks for replying, before I close the issue:
- what is total?
- how is height so near to the number of additions (>1.6m) with 10 subtrees & the no of UTXos way less than that ( u said it's the pol no here >0.4m)?
.
-Ofcourse I know these plots r not in #257 but I thought maybe u have done them at some stage of the project.
Thanks for replying

**Comment by kcalvinalvin** [comment]
>     * what is total?

Ah missed that. total is the total time the binary has been verifying the utreexo proofs. You can see how this is calculated here: https://github.com/mit-dci/utreexo/blob/ed904d7f0b9124cb2dc5b7189255ebbe2b3ca509/csn/ibd.go#L42-L90

> how is height so near to the number of additions (>1.6m) with 10 subtrees & the no of UTXos way less than that ( u said it's the pol no here >0.4m)?

Not quite sure what you mean. Are you saying asking `why are additions and UTXOs different?`?

**Comment by Shymaa-Arafat** [comment]
> Not quite sure what you mean. Are you saying asking why are additions and UTXOs different??

No, I'm asking howcome the no of UTXOs is much less than the tree height?(about quarter the height)

**Comment by kcalvinalvin** [comment]
> No, I'm asking howcome the no of UTXOs is much less than the tree height?(about quarter the height)

Because the height of the entire forest is O(log N). I encourage you to watch this [video](https://www.youtube.com/watch?v=edRun-6ubCc) and read the [paper](https://eprint.iacr.org/2019/611.pdf) to get a basic idea of how Utreexo works.

**Comment by Shymaa-Arafat** [comment]
There is something wrong here, either u didn't read my previous reply or u r reading/seeing something else than I wrote ...
 There's some kind of penetration.
1654444 can never be O(log N), it's O(add) here ... or that's what I am seeing/reading here????

**Comment by kcalvinalvin** [comment]
> There is something wrong here, either u didn't read my previous reply or u r reading/seeing something else than I wrote ...
> There's some kind of penetration.
> 1654444 can never be O(log N), it's O(add) here ... or that's what I am seeing/reading here????

Ah sorry he is hashes-ever not height. Edited the original reply.
