### ISSUE TITLE
FlatterTTL branch concurrency issues

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#276]
In flatterTTL, sending a sigint will result in a deadlock. In the `BlockAndRevReader()` goroutine, `wg.Add(2)` is called and the `FlatFileWriter()` goroutine calls the `wg.Done()`s.

However, when sigint is called, we break out of the main loop here

https://github.com/mit-dci/utreexo/blob/68421536a96fccd29636386304e3a8589f6f6304/bridgenode/genproofs.go#L99

and will wait for `fileWait` here
https://github.com/mit-dci/utreexo/blob/68421536a96fccd29636386304e3a8589f6f6304/bridgenode/genproofs.go#L149-L150

But the `BlockAndRevReader()` goroutine will still try to send to the `blockAndRevProofChan`, resulting in a deadlock since the main loop already broke out and isn't reading from the `blockAndRevProofChan` channel anymore. But we're still doing `wg.Add(2)`, so we just end up waiting for the `fileWait.Done()` forever.

https://github.com/mit-dci/utreexo/blob/68421536a96fccd29636386304e3a8589f6f6304/bridgenode/rev.go#L81-L84

**Comment by adiabat** [comment]
OK I fixed the signal handling here, so it seems to quit fine. 
Recovery doesn't work though; something about the txid index file either isn't getting all the data it should at the end, or the resume process is going too far ahead.  There's some small gap where after restart it tries to read beyond the end of the file, though usually not right away, as it successfully processes quite a few blocks before crashing.  Will try to fix that; if you see anything, let me know here or IRC.
