### ISSUE TITLE
Can the coinbase input be anything other than len == 1?

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#290]
https://github.com/mit-dci/utreexo/blob/7d436ce11280c3f0e2fd7b4f56e43d012125b811/bridgenode/processblock.go#L194-L194

https://github.com/mit-dci/utreexo/blob/7d436ce11280c3f0e2fd7b4f56e43d012125b811/bridgenode/processblock.go#L220-L221

In the code above (line 220 and 221), we're assuming that txin for a coinbase is variable. Is this true?

**Comment by JeremyRubin** [comment]
IIRC you can spend other coins into the CB txn

**Comment by kcalvinalvin** [comment]
> IIRC you can spend other coins into the CB txn

Oh huh, TIL. Thanks!
