### ISSUE TITLE
Use Enums for forest types

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#294]
We have 4 different types of forest and the way to specify each one of them is with an argument. It'd be a lot cleaner to implement these as golang enums (example - yourbasic.org/golang/iota/) instead of having many function arguments.

https://github.com/mit-dci/utreexo/blob/7d436ce11280c3f0e2fd7b4f56e43d012125b811/accumulator/forest.go#L96-L117

We'd have to change this function and then make changes to all the functions that call `NewForest()`.

**Comment by rohunmsharman** [comment]
Is this what you meant? I am a little unsure as this only removes one function argument. 
<img width="845" alt="enumForestType" src="https://user-images.githubusercontent.com/66086705/126711049-abece061-4e34-4ce1-ae21-c208ed92cdcf.png">

**Comment by r-ush** [comment]
@kcalvinalvin I have sent a PR that solves this issue. 😃

**Comment by kcalvinalvin** [comment]
> Is this what you meant? I am a little unsure as this only removes one function argument.

Yes that is what I meant. Though the `NewForest()` function should not be a method on the type.
