### ISSUE TITLE
ttl values on BuildProofs

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#34]
https://github.com/mit-dci/utreexo/blob/96839b818a88211a61e928f66b59c520f8166873/cmd/ibdsim/parsetxo.go#L80

So it seems we need the ttl values for caching. Can't get rid of them...

**Comment by kcalvinalvin** [comment]
I guess the deathHeight lookup can be done during BuildProofs().

Not sure how much overhead this adds but should still be faster....?
Anyways, I'll be implementing this for now

**Comment by adiabat** [comment]
plusline wants it but BuildProofs never actually uses it.  So we can get rid of this error

https://github.com/mit-dci/utreexo/blob/2bb667529c52ee7e3e35a70ba9f2ebb4b2113fc0/cmd/ibdsim/parsetxo.go#L53-L56

(and then have a check at line 80 so it doesn't go out of slice bounds) 
leave em uninitialized and then they'll just stay at 0, which should be fine for BuildProofs.
