### ISSUE TITLE
What is the variable fullHeight?

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#40]
https://github.com/mit-dci/utreexo/blob/f6c114d19f47b7027a2c89892b3e04bb55fb6253/utreexo/forest.go#L28

In this comment, a variable named fullHeight is referenced but ```git grep fullHeight``` doesn't return anything else than that comment.

https://github.com/mit-dci/utreexo/blob/f6c114d19f47b7027a2c89892b3e04bb55fb6253/utreexo/forest.go#L27-L29

Also, wouldn't a forest of 6 nodes have a ```var height``` that is 2 higher than the tallest tree? Is fullHeight something different from the ```var height uint8``` mentioned here?

**Comment by adiabat** [comment]
fixed in 6faa939b7a60291c2e00abdc58ef961e11fb2272
