### ISSUE TITLE
UTXOs have negative duration

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#44]
ttldb returns 0 if the tx wasn't found and all the utxos end up having negative duration since 

```deathheight - height```

is applied to all txos. So the ones that get 0 returned have negative duration.

In the older commits with the .txos files, the 0 heights had "s" appended to them. What should we do for these now?

**Comment by kcalvinalvin** [comment]
ok so "s" are given 1,000,000 (1 << 20).

Should this be implemented?

**Comment by adiabat** [comment]
I think this is OK?  A little ugly but have some large value (could be 1<<30) for txos which stay unspend forever.
