### ISSUE TITLE
Code style guide

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#48]
I think it would be good to introduce some basic code formatting stuff. Commit 967935a7fdd0dc3ffd42a0c4127b8687006c132e was just for code reformatting so it'd be helpful to have some guidelines.

Ex: Should I be doing two spaces? All comments by me have one space after a period but yours have two. 

I guess some other stuff like error handling would be good to write down. I've seen other go people do
```
err := func(); if err != nil {
        return err
    }
```

but we do

```
err := func
if err != nil {
        return err
}
```

Maybe write down guides as they come up?

**Comment by adiabat** [comment]
Good point and overdue, now uploaded here:
https://github.com/mit-dci/utreexo/blob/master/style.md
