### ISSUE TITLE
cleanup() really slow

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#55]
https://github.com/mit-dci/utreexo/blob/1527be3ba72c754a0da73c3ba7174f5253cd18dc/utreexo/forest.go#L254-L260

This is the offending line. Commenting it out seems to make a ***drastic*** improvement in performance.

**Comment by kcalvinalvin** [comment]
I should mention that commenting out that line made ```genproofs``` go from 8m17sec to 8.21sec when done up to block height 15463

**Comment by adiabat** [comment]
oops, yeah that `p < 1<<f.height` is way off, doing millions of deletions of things that aren't there anyway... every block.

fixed in 48e3456788a6185ab2d818d3a813e2c014b6cb5d
