### ISSUE TITLE
What is var tagRow?

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#58]
https://github.com/mit-dci/utreexo/blob/48e3456788a6185ab2d818d3a813e2c014b6cb5d/utreexo/blockproof.go#L150-L160

Not quite sure what's really going on here. What's the purpose of ```var tagRow``` and this code?

**Comment by ysangkok** [comment]
why close? you figured it out?

**Comment by kcalvinalvin** [comment]
Ah yeah, I figured it out a long time ago just didn’t bother to close it
