### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#61]
I can't think of any unit testing methods to test stuff in ```cmd/```.

I've been thinking that some sort of CI would be helpful for this project.

**Comment by adiabat** [comment]
yeah, I'm OK with travis if that's what everyone is used to.  A cmd benchmark / test would be useful, as well as running most of the _test.go files.  A bunch of them don't work though or are out of date or reference code that's gone, so I can clean up the unit test files.

**Comment by tnakagawa** [comment]
This is '.travis.yml' which I proposed before.
The installation needs to be modified.

```
language: go

go:
  - 1.x

install:
  - go get -u golang.org/x/lint/golint
  - go get -u golang.org/x/crypto/blake2b

script:
  - test -z "`gofmt -l .`"
  - test -z "`golint ./utreexo/...`"
  - go test -v ./utreexo/...
```
