### ISSUE TITLE
Weird unreachable code in forest.go

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#64]
https://github.com/mit-dci/utreexo/blob/d9ab388431f0e04662dfffe481ba7cf9a6d32c36/utreexo/forest.go#L136-L140

Not quite sure if line 138 is supposed to be the right thing or if line 139 is supposed to be the right thing to be called.

**Comment by adiabat** [comment]
Really neither should happen, as .from and .to should never be equal.  And it never seem to happen, I'll get rid of 139 & 140

**Comment by adiabat** [comment]
fixed in 912eb23a04aabc3ccac02aecab162c1ddf758e25
