### ISSUE TITLE
Is leafPrune() still used

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#70]
https://github.com/mit-dci/utreexo/blob/912eb23a04aabc3ccac02aecab162c1ddf758e25/utreexo/pollardutil.go#L90-L98

git grep doesn't show any other code calling this. Is this still used?

**Comment by adiabat** [comment]
Nope nothing was calling it.  Removed in 37cc89b9da7ca42901dddf93147e111ea01dd944 & can always find it there if it's needed.
