### ISSUE TITLE
Is totalProofNodes used for anything right now?

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#81]
https://github.com/mit-dci/utreexo/blob/2a4ab577d58b09748e858c4c1c879f4ac56a8d5d/cmd/ibdsim/genproofs.go#L194

I had left it there but is it used? Not sure if I can remove it or not

**Comment by adiabat** [comment]
Looks like it isn't, but at some point it was tracking total data sent as proofs, and it could still be useful for that if we put hooks in to increment it in places.

**Comment by ysangkok** [comment]
I think it hurts readability a lot to have unused stuff laying around. A casual reader is distracted, trying to understand something, only to finally figure out that it was not needed. It is better to keep unfinished code in other branches.

**Comment by adiabat** [comment]
Closing as this variable is gone now, and agreed we should clean up and remove unused code / variables.
