### ISSUE TITLE
panic: mkdir: no such file or directory

### ISSUE THREAD

**Issue by ysangkok** [mit-dci/utreexo#87]
commit 8d2c5a18d7e11b8a2e62340f636de5ad0a506044

```
Building offsetfile... blk01975.dat
Building offsetfile... blk01976.dat
Building offsetfile... blk01977.dat
Building offsetfile... blk01978.dat
Building offsetfile... blk01979.dat
got non magic bytes 00000000, finishing
Building offsetfile... blk01980.dat
blk01980.dat doesn't exist; done building
Creating new forestdata
panic: mkdir : no such file or directory

goroutine 1 [running]:
github.com/mit-dci/utreexo/cmd/bridgenode.BuildProofs(0xc0000aa200, 0x0, 0x0, 0x0, 0x0, 0xc00010e000, 0x0, 0x0)
	/home/janus/go/src/github.com/mit-dci/utreexo/cmd/bridgenode/genproofs.go:52 +0x877
main.main()
	/home/janus/go/src/github.com/mit-dci/utreexo/cmd/main.go:55 +0x296
```

In the source code, it seems like this error could occur if ttl files are missing. I don't think I generated those, as genproofs was the first command I ran. The readme doesn't mention generating ttl files, but I see it in the help of genproofs. Did I do something wrong?

**Comment by kcalvinalvin** [comment]
Hmm ok so part of ```genproofs``` job is to also generate the ```ttldb``` (or ```ttldb-testnet```) so it's not like you're doing anything wrong. Looks like the part where leveldb is trying to be opened/created is failing for you.

```
	} else if os.IsNotExist(err) && !readOnly {
		if err := os.MkdirAll(path, 0755); err != nil {
			return nil, err
```
in is generating the error for you.
https://github.com/syndtr/goleveldb/blob/758128399b1df3a87e92df6c26c1d2063da8fabe/leveldb/storage/file_storage.go#L99-L101

I've tested https://github.com/mit-dci/utreexo/commit/8d2c5a18d7e11b8a2e62340f636de5ad0a506044 on ```Darwin 19.3.0``` and ```Linux 5.3.11``` and cannot recreate the bug.

@adiabat Can you recreate this bug?

Side note but are you resuming based off a previously created data not based on commit https://github.com/mit-dci/utreexo/commit/8d2c5a18d7e11b8a2e62340f636de5ad0a506044? That might be another cause of failure.

**Comment by kcalvinalvin** [comment]
Could you provide the following?

1. Go version (```go version```)
2. Commit hash of the github.com/syndtr/goleveldb that you're building off of
3. Operating system && the version being used

**Comment by ysangkok** [comment]
the goleveldb commit in /home/janus/go/src/github.com/syndtr/goleveldb is 758128399b1df3a87e92df6c26c1d2063da8fabe

regarding the other information:

```
 % lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
 % go version
go version go1.13.4 linux/amd64
```

**Comment by adiabat** [comment]
I'm not sure; I can't reproduce this either.  It seems like a file permissions problem, where levelDB can't create the `ttldb-testnet` folder.  It created the other folders prior to that though, so looks like write permission is OK.  I changed the code to not have a dash in the folder name (though... why would that matter?)  
Try it with the new code and see if you get the same error?
Also - thanks for trying it out!

**Comment by ysangkok** [comment]
I was trying this on mainnet, maybe that is the issue?

**Comment by kcalvinalvin** [comment]
> I was trying this on mainnet, maybe that is the issue?

Ok I reproduced the issue

**Comment by adiabat** [comment]
OK found it; folder names were not initialized properly in mainnet.  Should work now with baeba5791ed92d7cbdc319abcafde6f4f2ba7d61

**Comment by kcalvinalvin** [comment]
Thanks @ysangkok. Gah dumb mistake by me :(

**Comment by ysangkok** [comment]
thanks!
